In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("D:\Downloads\TE-3_18_19.xlsx")
df

    ROLL NO                 NAME OF STUDENTS
0         1          NANGARE ABHISHEK TANAJI
1         2          MAHAJAN ADITYA RAJENDRA
2         3          MORADE AJINKYA RAJENDRA
3         4          SAUDAGAR AVINASH DAGADU
4         5            PATIL DHANANJAY SUNIL
5         6              ADHAV SAYALI SANJAY
6         7             SHINDE NIKHIL SHARAD
7         8           SHARMA NISHANK SANTOSH
8         9        GAJAKOSH NITESH TULSHIRAM
9        10               KOKARE OMKAR ASHOK
10       11            YADAV OMKAR BABASAHEB
11       12  KULKARNI PRATHAMESH BHALCHANDRA
12       13          PATIL PRITESH PRABHAKAR
13       14              SHETE SAIRAJ SHARAD
14       15          PANASKAR SANDESH SURESH
15       16         SHINDE SAURABH BADASHAHA
16       17    ABHISHEK SHRIKRUSHNA MADANKAR
17       18             MAGAR SHUBHAM DEEPAK
18       19            PATIL SHUBHAM SHIVAJI
19       20           DHUMAL SIDDHESH DHUMAL
20       21            WADKAR SMITHIL MARUTI
21       22             GAIKWAD SURAJ BHARAT
22       23        BASVEKAR MUKESH BADRINATH
23       24         SHUBHAM SHAILENDRA BOLLA
24       25            DESHMANE ANIKET ASHOK
25       26             DHAVALE SEJAL ANKUSH
26       27              GAIKWAD ANIKET RAJU
27       28                HARIP AMOGH SUHAS
28       29      SARVADE ABHIJEET SHATRUGHNA
29       30            JAISWAL SHUBHAM VIJAY
30       31             KAKADE DIVYA VISHWAS
31       32             KARAD BALAJI SITARAM
32       33           LOHAR SAMIKSHA SANTOSH
33       34        CHOUDHARY MAMATA SHIVSGAR
34       35             SHIVADE DIPAK CHHOTU
35       36          WAGHMARE PRAJWAL KISHOR
36       37           MULGE MAHADEV CHENNAPA
37       38           JAGADALE AKSHAY SANJAY
38       39             SARPE MUKESH PRADEEP
39       40         DHERE BHOOSHAN PAMESHWAR

In [3]:
df['NAME OF STUDENTS'] = [i.title() for i in df['NAME OF STUDENTS']]

In [4]:
df.head()

   ROLL NO         NAME OF STUDENTS
0        1  Nangare Abhishek Tanaji
1        2  Mahajan Aditya Rajendra
2        3  Morade Ajinkya Rajendra
3        4  Saudagar Avinash Dagadu
4        5    Patil Dhananjay Sunil

In [5]:
df.to_csv("roll_call.csv")

In [6]:
df.shape

(40, 2)

**SEMESTER THEORY ATTENDANCE**

In [7]:
import random
import pandas as pd
import numpy as np
import datetime
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

def te_students_attendance31(n, start_date, end_date):
    
    students = range(n)
    
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=start_date, end=end_date)
    
    custom_business_day = CustomBusinessDay(weekmask='Mon Tue Thu Fri', holidays=holidays)

    date_range = pd.date_range(start=start_date, end=end_date, freq=custom_business_day)
    
    attendance_records1 = {}
    
    for student in students:
        attendance_records1[student] = []
        
        for day in date_range:
            attendance_records1[student].append('P' if random.random() < 0.85 else 'A')
                
    df = pd.DataFrame.from_dict(attendance_records1, orient='index', columns=date_range)
    df['Present'] = df.apply(lambda x: x[x == 'P'].count(), axis=1)
    df['Absent'] = df.apply(lambda x: x[x == 'A'].count(), axis=1)
    df['%Att'] = round(df['Present'] / len(date_range) * 100,2)
    df['UT1'] = [random.randint(10,30) for i in range(0,n)]
    df['PREL'] = [random.randint(26, 65) for i in range(0, n)]
     
    return df

In [8]:
sem_att = pd.concat([df, te_students_attendance31(40, '2018-12-24', '2019-03-19')], axis = 1)
sem_att.to_csv("Sem_att.csv")

In [9]:
sem_att

,ROLL NO,NAME OF STUDENTS,2018-12-24 00:00:00,2018-12-27 00:00:00,2018-12-28 00:00:00,2018-12-31 00:00:00,2019-01-03 00:00:00,2019-01-04 00:00:00,2019-01-07 00:00:00,2019-01-08 00:00:00,...,2019-03-12 00:00:00,2019-03-14 00:00:00,2019-03-15 00:00:00,2019-03-18 00:00:00,2019-03-19 00:00:00,Present,Absent,%Att,UT1,PREL
0,1,Nangare Abhishek Tanaji,A,P,P,P,P,P,P,P,...,P,P,P,P,P,41,5,89.13,19,31
1,2,Mahajan Aditya Rajendra,P,P,A,P,P,P,P,P,...,P,P,P,P,P,40,6,86.96,15,64
2,3,Morade Ajinkya Rajendra,P,A,P,P,P,P,A,A,...,P,P,A,P,P,38,8,82.61,30,64
3,4,Saudagar Avinash Dagadu,P,P,A,P,P,P,P,P,...,P,P,P,P,P,41,5,89.13,14,26
4,5,Patil Dhananjay Sunil,P,A,P,P,P,P,P,P,...,A,P,P,P,P,39,7,84.78,24,45
5,6,Adhav Sayali Sanjay,P,P,P,P,P,P,A,P,...,P,P,P,P,A,37,9,80.43,10,32
6,7,Shinde Nikhil Sharad,P,P,P,P,P,P,P,P,...,P,P,P,P,P,40,6,86.96,22,46
7,8,Sharma Nishank Santosh,P,P,P,P,P,P,P,P,...,A,P,P,P,P,42,4,91.30,10,33
8,9,Gajakosh Nitesh Tulshiram,P,P,P,P,A,P,A,P,...,P,P,A,P,P,34,12,73.91,29,56
9,10,Kokare Omkar Ashok,P,P,P,P,P,P,P,P,...,P,P,P,P,P,40,6,86.96,26,41
10,11,Yadav Omkar Babasaheb,P,A,P,A,P,P,P,A,...,P,P,P,P,P,40,6,86.96,17,56
11,12,Kulkarni Prathamesh Bhalchandra,P,P,A,P,P,A,P,A,...,P,P,P,P,P,36,10,78.26,13,40
12,13,Patil Pritesh Prabhakar,P,P,P,P,P,P,A,P,...,P,P,P,A,P,36,10,78.26,30,31
13,14,Shete Sairaj Sharad,P,P,P,P,P,P,P,P,...,P,P,P,P,P,42,4,91.30,10,35
14,15,Panaskar Sandesh Suresh,P,P,A,P,P,A,A,P,...,P,P,A,P,P,35,11,76.09,17,43
15,16,Shinde Saurabh Badashaha,P,P,A,P,A,P,P,P,...,P,P,P,P,P,39,7,84.78,15,49
16,17,Abhishek Shrikrushna Madankar,A,P,P,P,P,P,P,P,...,P,P,P,P,P,41,5,89.13,29,30
17,18,Magar Shubham Deepak,A,P,P,P,A,P,P,A,...,P,A,A,P,P,33,13,71.74,18,60
18,19,Patil Shubham Shivaji,A,P,P,P,P,A,P,P,...,P,P,P,P,P,38,8,82.61,16,64
19,20,Dhumal Siddhesh Dhumal,A,P,P,A,P,P,P,P,...,A,P,P,P,P,37,9,80.43,17,28
20,21,Wadkar Smithil Maruti,P,P,P,P,P,P,A,P,...,P,P,P,P,P,42,4,91.30,26,33
21,22,Gaikwad Suraj Bharat,P,P,P,P,P,P,P,P,...,P,A,P,P,A,39,7,84.78,25,40
22,23,Basvekar Mukesh Badrinath,P,P,P,P,P,P,P,P,...,A,P,P,P,P,36,10,78.26,20,35
23,24,Shubham Shailendra Bolla,P,P,P,P,P,P,P,P,...,P,P,P,P,P,44,2,95.65,25,55
24,25,Deshmane Aniket Ashok,P,A,P,P,P,P,P,P,...,P,P,A,P,P,39,7,84.78,26,57
25,26,Dhavale Sejal Ankush,P,P,P,P,P,P,P,P,...,P,P,P,P,P,38,8,82.61,21,56
26,27,Gaikwad Aniket Raju,P,P,P,P,P,A,P,A,...,A,A,P,P,P,34,12,73.91,20,29
27,28,Harip Amogh Suhas,P,A,P,A,P,P,P,P,...,P,P,P,P,P,40,6,86.96,27,65
28,29,Sarvade Abhijeet Shatrughna,P,P,P,P,P,A,P,P,...,P,P,P,A,P,40,6,86.96,17,32
29,30,Jaiswal Shubham Vijay,A,P,P,P,P,P,A,P,...,P,A,P,P,P,41,5,89.13,15,57
30,31,Kakade Divya Vishwas,P,P,P,A,P,P,P,P,...,P,P,P,P,P,38,8,82.61,16,30
31,32,Karad Balaji Sitaram,P,P,P,P,A,P,P,A,...,P,P,P,P,P,42,4,91.30,27,47
32,33,Lohar Samiksha Santosh,P,P,P,P,P,P,P,P,...,P,P,P,P,P,39,7,84.78,24,44
33,34,Choudhary Mamata Shivsgar,P,A,P,P,P,P,P,A,...,P,A,A,P,A,34,12,73.91,23,51
34,35,Shivade Dipak Chhotu,P,P,P,P,P,P,P,P,...,P,A,P,P,P,41,5,89.13,26,54
35,36,Waghmare Prajwal Kishor,P,P,P,P,P,A,P,P,...,A,P,P,P,P,41,5,89.13,13,29
36,37,Mulge Mahadev Chennapa,P,A,P,A,P,A,P,P,...,A,P,A,P,P,36,10,78.26,28,26
37,38,Jagadale Akshay Sanjay,P,P,P,P,P,P,P,P,...,P,P,P,P,P,42,4,91.30,22,59
38,39,Sarpe Mukesh Pradeep,A,P,P,P,P,P,P,P,...,P,P,A,P,P,41,5,89.13,28,64
39,40,Dhere Bhooshan Pameshwar,P,P,P,P,P,A,P,P,...,P,P,A,A,P,36,10,78.26,17,45

**FIRST MONTHLY ATTENDANCE**

In [10]:
first_month_att = pd.concat([df, te_students_attendance31(40, '2018-12-24', '2019-01-24')], axis = 1)
first_month_att.to_csv("First_Month_Att.csv")

In [11]:
first_month_att.head()

,ROLL NO,NAME OF STUDENTS,2018-12-24 00:00:00,2018-12-27 00:00:00,2018-12-28 00:00:00,2018-12-31 00:00:00,2019-01-03 00:00:00,2019-01-04 00:00:00,2019-01-07 00:00:00,2019-01-08 00:00:00,...,2019-01-15 00:00:00,2019-01-17 00:00:00,2019-01-18 00:00:00,2019-01-22 00:00:00,2019-01-24 00:00:00,Present,Absent,%Att,UT1,PREL
0,1,Nangare Abhishek Tanaji,A,P,P,P,P,P,P,P,...,P,A,P,P,P,13,3,81.25,13,33
1,2,Mahajan Aditya Rajendra,P,P,A,P,A,P,P,A,...,P,P,P,P,P,12,4,75.00,23,59
2,3,Morade Ajinkya Rajendra,P,P,A,P,P,A,P,P,...,P,P,P,P,P,14,2,87.50,23,51
3,4,Saudagar Avinash Dagadu,P,P,P,P,P,P,P,P,...,P,P,P,P,P,16,0,100.00,25,46
4,5,Patil Dhananjay Sunil,A,P,P,P,P,P,P,P,...,P,P,P,P,P,15,1,93.75,13,57

**SECOND MONTH THEORY ATTENDANCE**

In [12]:
second_month_att = pd.concat([df, te_students_attendance31(40, '2019-01-25', '2019-02-25')], axis = 1)
second_month_att.to_csv("Second_Month_Att.csv")

In [13]:
second_month_att.head()

,ROLL NO,NAME OF STUDENTS,2019-01-25 00:00:00,2019-01-28 00:00:00,2019-01-29 00:00:00,2019-01-31 00:00:00,2019-02-01 00:00:00,2019-02-04 00:00:00,2019-02-05 00:00:00,2019-02-07 00:00:00,...,2019-02-15 00:00:00,2019-02-19 00:00:00,2019-02-21 00:00:00,2019-02-22 00:00:00,2019-02-25 00:00:00,Present,Absent,%Att,UT1,PREL
0,1,Nangare Abhishek Tanaji,P,P,A,P,P,P,P,P,...,P,P,P,P,P,15,2,88.24,29,50
1,2,Mahajan Aditya Rajendra,P,P,P,P,P,P,P,P,...,P,P,P,A,P,15,2,88.24,25,61
2,3,Morade Ajinkya Rajendra,P,P,P,P,P,P,P,P,...,P,P,P,P,A,15,2,88.24,13,44
3,4,Saudagar Avinash Dagadu,P,P,P,P,A,P,P,P,...,P,A,A,A,A,11,6,64.71,15,50
4,5,Patil Dhananjay Sunil,A,P,P,P,A,P,A,A,...,P,A,P,P,P,12,5,70.59,17,52